### PR TITLE
Resolves issue #24 - Add support for stdin matching.

### PR DESCRIPTION
**Pull request by ckstettler**
Add feature for --match-stdin and --stdin-match-type arguments to allow testers to mock and match functions based on stdin as well as the argument list.

### CODE REVIEW

**Comment by ckstettler** [comment]
@CaptainQuirk would you want to look at this one as well?  This was your request.  I added additional options to allow matching on stdin.  I treat them separately meaning you can match on one or the other or both.  If both are provided it is basically an AND of the two that determines whether they match.

Also were you ever able to see merge buttons?  I have been trying to give you that permission but we have had some challenges it seems.

**Comment by CaptainQuirk** [comment]
Thanks @ckstettler ! I'll get to it next week !

**Comment by tyleroconnell** [comment]
@CaptainQuirk no worries if you don't have time to review this, just want to make sure that's the case before I take a look

**Review by tyleroconnell — APPROVED** [review]
LGTM

**Pull request merged**
